version: '3.7'
services:
  flighttrack-db:
    image: mysql:5.7
    container_name: flighttrack-db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=flighttrack
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - db
  flighttrack-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: flighttrack-app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    networks:
      backend:
        aliases:
          - flighttrack-app
networks:
  backend:
    name: backend-network
